spring:
    datasource:
        url: jdbc:postgresql://cona5.co.kr:5432/invenm?characterEncoding=UTF-8
        username: invenadmin
        password: dlsqps4321
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true

logging:
    level:
        org:
            hibernate:
                sql: INFO
                tool:
                    hbm2ddl: INFO
            springframework: INFO
        root: INFO